### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [orgzly-revived/orgzly-android-revived#107]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5633763291#L1565

ref: https://github.com/orgzly-revived/orgzly-android-revived/pull/97/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R106

ref: F-Droid [list of "trusted" maven repos](https://gitlab.com/fdroid/fdroidserver/-/blob/2a60f6c195dfd24149617ceb1df1731fb3bf50c8/fdroidserver/scanner.py#L452-L471)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/69b305106b18d076d8a00c253f110baa7a7eab71

**Comment by licaon-kter** [comment]
Maybe this dependency can be built from source? But where is its source exactly?

**Comment by amberin** [comment]
Whoops... I actually thought to myself that I should probably be more careful about adding repos. I'll look into it.

**Comment by amberin** [comment]
I will try to use this one instead: https://mvnrepository.com/artifact/javax.management/jmxri/1.2.1

**Comment by amberin** [comment]
@licaon-kter Thanks a million for creating the issue - I had not noticed as I don't install via Fdroid myself.

**Comment by licaon-kter** [comment]
@amberin a good reason to start :)

_(well, as a user you won't notice this; but as a dev you could if you'd use fdroidserver images to actually build the app in github actions)_

**Comment by amberin** [comment]
@licaon-kter sounds like a great thing to do for release builds!

**Comment by amberin** [comment]
> if you'd use fdroidserver images to actually build the app in github actions

@licaon-kter Do you already know how this would be done? I found [this image](https://gitlab.com/fdroid/docker-executable-fdroidserver), but I'm confused about if/how we could use it.

There's [an Action in the marketplace for building nightly builds](https://github.com/marketplace/actions/f-droid-nightly-builds) but when I tried that it tries to clone our repo and fails.

**Comment by licaon-kter** [comment]
> it tries to clone our repo and fails.

I have no experience with the Docker thing, but do post the whole error message

**Comment by licaon-kter** [comment]
do reopen this

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7211355255

@linsui tried locally with zipalign but does not seem to help with 16, 64

any ideas?

**Comment by amberin** [comment]
> @linsui tried locally with zipalign but does not seem to help with 16, 64

What does "16, 64" refer to?

There are no changes to the build process between 1.8.23 and 1.8.24, for what it's worth.

**Comment by licaon-kter** [comment]
file:///android_asset/md/#zipalignpy

And some context in follow up comments here: https://github.com/devhyper/open-video-editor/issues/63#issuecomment-2140433666

**Comment by linsui** [comment]
https://github.com/orgzly-revived/orgzly-android-revived/blob/master/build.gradle#L7 AGP is not 8.3+. Does page size 4 work?

**Comment by licaon-kter** [comment]
align 4 does not change the APK sha256sum, so I guess it's already 4

**Comment by licaon-kter** [comment]
just tested 4 (zipalign from debian) and success....what the.,.,..

**Comment by licaon-kter** [comment]
we've figured out what changed, see https://gitlab.com/fdroid/fdroiddata/-/issues/3299#note_1985568674

so around here, I guess: https://github.com/orgzly-revived/orgzly-android-revived/blob/v1.8.24/.github/workflows/release.yml#L43 make it do `apksigner sign --alignment-preserved true  ...` (you are using some other external actions so not sure how to inject that in https://github.com/r0adkll/sign-android-release/blob/f30bdd30588842ac76044ecdbd4b6d0e3e813478/lib/signing.js#L66 )

eg. others have another setup like: https://github.com/ImranR98/Obtainium/blob/v1.1.13/.github/workflows/release.yml#L75

**Comment by amberin** [comment]
@licaon-kter Thanks. I'll try using build-tools 34 for our next release, and then keep an eye on what happens on Google's end.

**Comment by obfusk** [comment]
> I suppose if you guys could implement the third option suggested by obfusk, it would save a lot of people a lot of trouble... 🙏

I've [documented that now](https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1). It's trivial to add it to a build recipe.

**Comment by licaon-kter** [comment]
@amberin per the docs above, we've added the workaround in the F-Droid recipe, there's no need to change anything for now

ref: https://gitlab.com/fdroid/fdroiddata/-/commit/72de7791415a9c4b3f7e4da1bcf80717eb2ffe8e

feel free to star the Google issue https://issuetracker.google.com/issues/351408623
