### ISSUE TITLE
Leverage timestamps in properties drawers

### ISSUE THREAD

**Issue by Trevoke** [orgzly-revived/orgzly-android-revived#126]
- [x] I have searched for existing issues that may be the same as or related to mine.

This is a re-opening of issue https://github.com/orgzly/orgzly-android/issues/640 from original orgzly.

According to org-mode, the SCHEDULED timestamps are for when something is supposed to start and the DEADLINE timestamps are for when something is supposed to end.

For plain ol' events, we should use plain ol' timestamps.

I am the author of https://github.com/Trevoke/org-gtd.el and in order to create a sufficiently automated tool, I am placing timestamps in the properties drawer. This works perfectly within emacs, unfortunately, orgzly does not search for timestamps there, so right now I'm forced to also add a timestamp in the body of the heading for orgzly users.

It would be absolutely fantastic if orgzly did leverage timestamps in properties drawers, at least for agenda views.

**Comment by amberin** [comment]
Cool, I wasn't familiar with org-gtd.el. 

The docs say "We use our own timestamp property". Are you thinking Orgzly would pick up any property containing a timestamp, and put that in the agenda?

**Comment by Trevoke** [comment]
As long as the timestamp is active, by default, it will be picked up by org-agenda ( https://orgmode.org/manual/Timestamps.html), yes.

When I say that I use a custom property, what I mean is `ORG_GTD_TIMESTAMP: <2023-12-25>`, that's all.

**Comment by Sabicool** [comment]
This would also be useful for packages other than org-gtd such as [org-review](https://github.com/brabalan/org-review) which utilise properties with time stamps.

**Comment by amberin** [comment]
I believe we should definitely add all active timestamps to the agenda, the same way as org-mode.
