### ISSUE TITLE
A blinding light...

### ISSUE THREAD

**Issue by blackICE19240** [orgzly-revived/orgzly-android-revived#139]
Imagine this:  It's 1am and you're trying to get to sleep - but you can't - your mind is racing, coming up with new idea after new idea. At some point you realise, that if you don't make records of these brilliant thoughts, they may be gone forever! Quickly, you reach for your phone and unlock it. The phone's low brightness and dark theme are only slightly uncomfortable on the eyes as you stretch your thumb to tap for your trusty notes app, BUT SUDDENLY, you are blinded by a searing light the instant the app opens! The light only last a moment before it disappears, _just as those thoughts did_. 
Please can you apply the dark theme to the opening animation too. As I am sure you can tell, it is very important  ;)

![3f7f81a9-119c-4839-9230-3936881814cd](https://github.com/orgzly-revived/orgzly-android-revived/assets/22436054/5bab4032-3097-4cf4-bc1f-9a2f1c6c2549)

- I have searched for existing issues that may be the same as or related to mine.

**Comment by amberin** [comment]
Solved by #141 and released in v1.8.15. Thank you very much for contributing!
