### ISSUE TITLE
Support Obtainium

### ISSUE THREAD

**Issue by Emiller88** [orgzly-revived/orgzly-android-revived#14]
https://github.com/ImranR98/Obtainium

If someone with permissions could [cut a pre-release like I have in my fork](https://github.com/Emiller88/orgzly-android/releases/tag/v1.8.11), then we'd be able to point people to download it with Obtainium while #7 gets figured out. 

https://github.com/orgzly-community/orgzly-android/issues/7

**Comment by Emiller88** [comment]
This might be useful https://github.com/marketplace/actions/signed-release-apk-publisher

**Comment by Emiller88** [comment]
@amberin That worked! Might be able to get some CI setup for whenever it get's tagged it'll autocreate a release and sign it.

**Comment by amberin** [comment]
> @amberin That worked! Might be able to get some CI setup for whenever it get's tagged it'll autocreate a release and sign it.

That would be ideal, because I assume that would make it easier to co-own the signing key.

I don't know why Obtainium didn't pick up the name change, but yes, apart from that it seems to work. I suppose there is some metadata file containing the name, but this was a "premium" build, not "fdroid", so I'm thinking the /metadata directory should not affect it?

**Comment by amberin** [comment]
Or maybe Obtainium always parses /metadata/LANG/title.txt?

**Comment by amberin** [comment]
I have suggested a solution in #16.

**Comment by amberin** [comment]
I have now published an official "prerelease" APK. I can add the app in Obtainium, but only via the repo URL. I wonder what it takes to make the app "Github-discoverable". The original repo has no Github releases, but it is still discoverable. :thinking:

**Comment by Emiller88** [comment]
Yeah I think the version regex is off with the prerelease... the real releases seemed to work.

**Comment by amberin** [comment]
I have now release v1.8.11 proper, but I still can't find us via search in Obtainium. :(

**Comment by Emiller88** [comment]
Ah, I just added the repo URL! The new version looks like it updated properly, I think it was the beta part that threw it off.

**Comment by Emiller88** [comment]
Okay, the new beta installed just fine! Not sure what changed, but I'm calling this done!

**Comment by amberin** [comment]
@Emiller88 That's great, but our app is still not searchable in Obtainium, as opposed to the original app. It can only be found by entering the exact repo URL. I don't think this is great, especially since the original app is fully searchable, I don't see why ours should be any different... :/

**Comment by Emiller88** [comment]
Hmm that's really weird I see it too. Maybe the tags? There's an android tag? Probably should open an issue with obtainium.

**Comment by kai11** [comment]
https://api.github.com/search/repositories?q=orgzly+revived

At the time of writing URL above returns 0 results.

https://api.github.com/search/repositories?q=fork:true+orgzly+revived

Returns 4 results, this repo is first.

Orgzly-revived is a fork for GitHub search engine.

**Comment by kai11** [comment]
On my own repos I don't see any way to "unfork" repository.
I think you should create duplcate for that.
Fork is intended for upstream contribution.

More info:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks#forking-a-repository-versus-duplicating-a-repository

**Comment by kai11** [comment]
For comparison:

https://api.github.com/search/repositories?q=syncthing+fork

Syncthing Fork by Catfriend1 is not fork at all (fork:false)

**Comment by amberin** [comment]
Good finds, @kai11. We've said that the goal is to contribute our work to the original app, if it resumes development. But this of course does nor require the "fork" status on our repo.

I'm worried that it seems hard to "unfork"... Setting up another repo would probably be quite some work, considering security settings, discussions, issues and PR history.

**Comment by kai11** [comment]
@amberin It's not that bad.
You can contact GitHub support - https://stackoverflow.com/a/16052845

**Comment by amberin** [comment]
> @amberin It's not that bad. You can contact GitHub support - https://stackoverflow.com/a/16052845

Great - I'll email them.

**Comment by amberin** [comment]
I have opened a ticket via Github's virtual assistant to "extract" our fork.

**Comment by amberin** [comment]
Our fork has been decoupled and is now no longer a fork. The app is now searchable in Obtainium.

I'm not sure if the difference between version tag and version name format will cause Obtainium to mis-identify, but let's handle any such problems separately. Closing this.
