### ISSUE TITLE
Org-Drill Support

### ISSUE THREAD

**Issue by Maddogskullcap** [orgzly-revived/orgzly-android-revived#143]
I have searched for existing issues that may be the same as or related to mine. I've seen one or two others mention it, but with the original unsupported orgzly. I do not know if this would be possible, but if you were to add the ability to use even a simple version Org-drill in Orgzly it would be able to compete with Anki as a mobile spaced-repetition learning tool. Ankidroid cannot sync with plaintext files like the desktop app, It uses Anki's server(that I personally don't feel comfortable syncing to) to sync decks, and setting up a self-hosted server is not well documented, and of course it's not Org. If you could pull off mobile Org-drill in Orgzly it'd be a major upgrade to pull those looking for Anki alternatives and could become a mainstream FOSS spaced-repetition learning tool. I believe it could bring a lot of good attention to Orgzly-android-revived. I can see how it may be out of scope, but Orgzly already has a lot of fantastic preexisting widgets and a great foundation to build off of.

**Comment by Ypot** [comment]
As org-drill is not included in emacs, maybe there should be first a discussion about the best package?

https://github.com/abo-abo/pamparam

https://github.com/l3kn/org-fc?tab=readme-ov-file
