### ISSUE TITLE
Filter syncthing generated conflict files

### ISSUE THREAD

**Issue by Ypot** [orgzly-revived/orgzly-android-revived#147]
- I have searched for existing issues that may be the same as or related to mine.

Inspired in an `orgcalc` feature, I suggest adding the option to ignore syncthing conflict files. So we don't have duplicate entries when syncthing generates a new file in the form of:  _original-file-name.sync-conflict-data-time-ID.org_

**Comment by amberin** [comment]
This seems like an easy thing to add. I don't use Syncthing myself - is there any risk that filtering out these files would lead to the user not becoming aware of the conflict?

**Comment by Ypot** [comment]
> This seems like an easy thing to add. I don't use Syncthing myself - is there any risk that filtering out these files would lead to the user not becoming aware of the conflict?

It could, but that is not the way to be aware of that.

Syncthing has a notification for it. And user would be unaware of any conflict not related with .org files.

**Comment by stfl** [comment]
You can use the `.orgzlyignore` file to do that

**Comment by amberin** [comment]
@stfl That file currently is currently only used in Git repos.

**Comment by Ypot** [comment]
I have added it to syncthing ignore pattern.
