### ISSUE TITLE
Unable to create/specify Git repo

### ISSUE THREAD

**Issue by clach04** [orgzly-revived/orgzly-android-revived#150]
- I have searched for existing issues that may be the same as or related to mine. Closest is https://github.com/orgzly-revived/orgzly-android-revived/issues/58

Using Android 10 phone.

I can generate an ssh key fine without problem, so slightly different from https://github.com/orgzly-revived/orgzly-android-revived/issues/58

But selecting the git repo does nothing. If I select Directory or WebDAV both bring up a dialog, Git brought up an Android permissions request for file access which I granted but now does nothing. Seen with FDroid install and the separate APK ([orgzly-revived-1.8.14.apk](https://github.com/orgzly-revived/orgzly-android-revived/releases/download/v1.8.14/orgzly-revived-1.8.14.apk)) from https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.14 

Is this user error or a bug (it feels like the later).

**Comment by amberin** [comment]
Hello, thank you for reporting. What Android version are you on?

**Comment by clach04** [comment]
Android 10 (I'll go back and update the original report).

**Comment by amberin** [comment]
Will see if I can recreate. If you can check the device logs (e.g. with an app such as Logcat Reader) and filter for orgzly, that would be great. I will suggest adding cloning errors to the "developer major events log".

**Comment by wilderjds** [comment]
I have a similar issue; git cloning fails silently; logcat is attached
[logcat_02-04-2024_23-31-12.txt](https://github.com/orgzly-revived/orgzly-android-revived/files/14160615/logcat_02-04-2024_23-31-12.txt)

**Comment by amberin** [comment]
> I have a similar issue; git cloning fails silently; logcat is attached [logcat_02-04-2024_23-31-12.txt](https://github.com/orgzly-revived/orgzly-android-revived/files/14160615/logcat_02-04-2024_23-31-12.txt)

Great, thank you. Which Android version are you on?

This error from JGit is something we have not seen before. I hope it might be an R8/minify issue.

**Comment by wilderjds** [comment]
Android 11 here. Please let me know if I can be of more help.

**Comment by amberin** [comment]
Seems to be this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=582423

I will look at downgrading JGit to 6.6.1 for now.

**Comment by amberin** [comment]
I think I have resolved the issues on Android 11, but on 10 it looks bad. It seems that our solution for external storage permission (0d0dc29c6e4b349fc67360e642dde1dd9e7eddd4) does not work on Android 10, and I don't know if it has ever worked.

The permission check is always negative, so we always end up in the "request permission" logic, but then nothing happens once you have answered the prompt one time. The Android GUI says that the app has "storage" permission, but I'm not sure what that really means.

If I change the logic to launch the activity, cloning fails because of missing write permissions.

**Comment by clach04** [comment]
Thanks for the detailed update @amberin as an Android 10 (potential) user that's a real pain 😿.

I know a few authors of Android apps that did not want to deal with android storage api, have ended up using the Android app "home" directory (which it sounds like https://github.com/orgzly-revived/orgzly-android-revived/issues/21 maybe suggesting?) as it was least hassle to develop. It doesn't rule out real permissions/API in the future.

**Comment by amberin** [comment]
I think I found and solved the permission problem on Android 10. I will open a PR after some testing.
