### ISSUE TITLE
Include/exclude specific org files/directories when syncing a git repo

### ISSUE THREAD

**Issue by stfl** [orgzly-revived/orgzly-android-revived#151]
I have a gtd/ directory in my org repo I want to use. It's all I need in orgzly. 
All the org-roam files and archives shall be ignored. 

This could be implemented by placing an. orgzlyignore file in the repo root with .gitignore semantics.

Configuring this via the gui would be great but for an mvp may be neglected.

**Comment by amberin** [comment]
Hmm, I thought we already had something like this... But I may be dreaming. I will look into it.

**Comment by amberin** [comment]
https://github.com/orgzly-revived/orgzly-android-revived/blob/288b229c432114be6445ef409acd2eae5b958fc8/app/src/main/java/com/orgzly/android/repos/GitRepo.java#L233 I have never tried it myself, but you should be able to use a file called .orgzlyignore.

**Comment by amberin** [comment]
Please close this issue if you try this out and it works. :pray:

**Comment by stfl** [comment]
I am currently struggeling newly creating the git repo as it silently fails. but that's another issue. I will test the orgzlyignore feature once I manage to setup the repo again.

**Comment by amberin** [comment]
@stfl If you can, please try out the latest prerelease, and see if it works better for you: https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.17-beta.1

**Comment by stfl** [comment]
Oh yes indeed. haven't thought about that. I cloned initially and hundreds of org files showed up from many levels down the dir tree (org-roam).
That was when I decided to open the issue here.

In my regular orgzly setup, I have my org repo cloned and synced with syncthing and only added the gtd dir to orgzly.

Maybe that was a simple workaround to only get what is inside the gtd dir with depth 1 (not gtd/archive/) without using the .orgzlyignore file.

**Comment by stfl** [comment]
I can confirm that the above .orgzlyignore file works now.
I am not sure if I changed something from a previously not working version or I had to clone freshly or restart.
Either way, I am very happy this works now and I can move to orgzly-revived now and drop my syncthing setup.
