### ISSUE TITLE
question dropbox support

### ISSUE THREAD

**Issue by isentropic** [orgzly-revived/orgzly-android-revived#152]
I understand that dropbox might be against the f-droid and stuff, but is there any other way to get it? I personally depend on it a lot as it seemed to be the most robust way of syncing for me

**Comment by amberin** [comment]
Hm, any other way than what? The APKs published as releases in this repo without the "fdroid" suffix are supposed to have Dropbox enabled just as before.

**Comment by isentropic** [comment]
ah great then

**Comment by pataquets** [comment]
Linking to solution issue: #35
