### ISSUE TITLE
Picking up changes in remote location

### ISSUE THREAD

**Issue by danielkrajnik** [orgzly-revived/orgzly-android-revived#165]
- I have searched for existing issues that may be the same as or related to mine. I believe that there is one already, but I couldn't find it so please correct me and close this one if that's the case.

I've tried editing one of the files orgzly-revived syncs with in another application, but orgzly doesn't pick up the changes in the remote file - instead it only complains that "last synced notebook and latest remote notebook differ".

Obviously it would be good if orgzly could pick up these changes so you could edit the notes in any application, not just orgzly.

**Comment by amberin** [comment]
Hello! Thanks for reporting. A few questions:

1. What type of repo are you using?
2. Does your repo contain any notebooks inside folders?
3. What Android version are you using?

**Comment by danielkrajnik** [comment]
@amberin Sorry, I've made a mistake. The issue wasn't caused by editing a single file by multiple applications.

I was trying to move my notebooks from previous location, which was a local directory to another directory. This cause the orgzly to give this error (which may be another bug).

I'll close this for now if you don't mind.

**Comment by danielkrajnik** [comment]
@amberin Sorry, I've made a mistake. The issue wasn't caused by editing a single file by multiple applications.

I was trying to move my notebooks from previous location, which was a local directory to another directory. This cause the orgzly to give this error (which may be another bug).

I'll close this for now if you don't mind.
