### ISSUE TITLE
Regression: Widget doesn't open

### ISSUE THREAD

**Issue by markokocic** [orgzly-revived/orgzly-android-revived#176]
Since the update to the latest Orgzly revived version from F-Droid, I am not able to open a widget any more.

When clicking on the widget, I get the following message: "Die App-Daten konnten nicht gelesen werden. Die App kann nicht gestartet we..."

I tried removing and adding the widget again, but it still doesn't work.

**Comment by stefan2904** [comment]
Both existing and new widgets work for me on 1.8.16. Do you have time to post your logcat output while attempting to add the widget?

**Comment by markokocic** [comment]
I added a "New note" widget from the shortcut, so this ticket is related to #177

**Comment by amberin** [comment]
@markokocic Do you mean that the "new note" widget works for you or not?

**Comment by markokocic** [comment]
It did not work in the last release, but seems like it's fixed in the beta you just published.
