### ISSUE TITLE
Dropbox token keeps expiring 

### ISSUE THREAD

**Issue by alexvorobiev** [orgzly-revived/orgzly-android-revived#195]
I have switched from the legacy Orgzly but now the synchronization with Dropbox keeps breaking due to the expiring tokens. Looking at their forums (e.g. https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Is-it-possible-to-get-a-permanent-token-for-uploading-files-to/td-p/712091), the client is supposed to request an "offline" token then accept a "refresh" token followed by a sequence of short-lived tokens "as needed". Does Orgzly do that or am I doing anything wrong?

**Comment by amberin** [comment]
All I know about the Dropbox repo implementation is that we haven't touched the code, so it should be no different than the original Orgzly code.

**Comment by alexvorobiev** [comment]
Could it be that my previous Orgzly used the now discontinued long term Dropbox token? I don't really understand how that might have been the case given that those tokens were discontinued back in 2022 and I got a new phone a few months ago (and Orgzly synchronization worked just fine). 

For now I switched to the local directory sync and use Dropsync app to synchronize it with Dropbox.

**Comment by amberin** [comment]
We need to change https://github.com/orgzly-revived/orgzly-android-revived/blob/master/app/src/main/java/com/orgzly/android/repos/DropboxClient.java#L87 according to https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Java-SDK-No-refresh-token/m-p/479296/highlight/true#M24198.

**Comment by amberin** [comment]
@alexvorobiev Did you by any chance create an app in your developer console and name it "Orgzly Revived"? Someone has apparently done that, and I'm hoping it might be you... I am unable to create an app with that name because it is "already taken". This prevents us from creating an app key to use with the release APK.

**Comment by alexvorobiev** [comment]
@amberin I did create an app called "orgzly revived" (all lowercase) when I was trying to fix the Dropbox sync issue. I have just deleted it.

**Comment by amberin** [comment]
> @amberin I did create an app called "orgzly revived" (all lowercase) when I was trying to fix the Dropbox sync issue. I have just deleted it.

@alexvorobiev Awesome! Thank you very much. I was now able to create it. I will add the app key to the release build, and there is now a PR to fix the expiring token issue.

**Comment by amberin** [comment]
@alexvorobiev If you can, please try out the new [beta build](https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.20-beta.1). It can be downloaded from the Releases page or installed via the Obtainium app.

**Comment by alexvorobiev** [comment]
@amberin I installed the beta. The "Link to Dropbox" button doesn't do anything.

**Comment by amberin** [comment]
@alexvorobiev Haha sorry, you are right, it's the same on my phone. I'll see what went wrong there.

Thank you for testing.

**Comment by amberin** [comment]
@alexvorobiev There is now a new beta build which works better.
