### ISSUE TITLE
recurring events dates

### ISSUE THREAD

**Issue by amigo421** [orgzly-revived/orgzly-android-revived#216]
not sure that is an issue but looks so for me:

1. e.g. I arrange an event on Mon with a repeat weekly. 
2. I didn't complete this at Mon (overdue) and was working on this at Tue and then marked this as Done. 
3. From my perspective next auto-scheduled event should be arranged on next Mon. But it's wrong - it's scheduled on on next Tue!!
4. So all my schedule is shifted !

could you fix this bug please? or probably make this an option

**Comment by dwoffinden** [comment]
It sounds like you used `.+1w` when you want `+1w` or `++1w`? It's an option when specifying the repeater. 

See also https://orgmode.org/manual/Repeated-tasks.html

**Comment by amigo421** [comment]
aah, apologies of my inattention , thanks a lot for a tip . I'm going to close the request
