### ISSUE TITLE
orgzlyignore does not correctly filter files

### ISSUE THREAD

**Issue by stfl** [orgzly-revived/orgzly-android-revived#226]
The `.orgzlyignore` file does not correctly filter notebooks.

Since subfolders do not work correctly yet, I moved all of my files to the repo root.
So my GTD files which I want in orgzly are mixed together with my org-roam files.

I tried several approaches, which did lead to the correct result.
Verified with `fd --ignore-file .orgzlyignore` that the glob syntax should work.

Initially I ignored all org files negated it only for files I want but changes to inbox.org are not written anymore.

```
*.org
!inbox.org
```

I have numerous files `YYYYMMDDhhmmss-name.org`, so I tried to selectivly ignore these but all notebooks showed up and changes are still written

```
/202*-*.org
```

**Comment by amberin** [comment]
Thank you for reporting! It's a good time to identify bugs like these, since I'm currently looking at #224.

I will see if I can reproduce on my own.

**Comment by stfl** [comment]
Ok, now I have a lot of files indicated as `Only local dummy exists`, which indicates to me, that the second iteration of `.orgzlyignore` did in fact work.
I will verify that at some point by cloning the repo again.

Although, the original issue stems from the ignore-all and reverse for specific files only.
