### ISSUE TITLE
Allow selecting multiple notebooks

### ISSUE THREAD

**Issue by amberin** [orgzly-revived/orgzly-android-revived#227]
✅ I have searched for existing issues that may be the same as or related to mine.

This should really not be that hard to implement. It is primarily needed for deleting multiple books, which is currently a big chore.

Original Orgzly issue: https://github.com/orgzly/orgzly-android/issues/749

**Comment by amberin** [comment]
I am working on this and it is going well.

**Comment by pjhfggij** [comment]
fantastic! thank you! as soon as 1.8.26 reaches fdroid I will report if this .orgzlyignore works for me:
```gitignore
# ignore everything by default
*

# except for "test.org"
!test.org

# except for files in folder "orgzly"
!orgzly/
!orgzly/*
```
