### ISSUE TITLE
Push notifications no worky when no SCHEDULED: property

### ISSUE THREAD

**Issue by pjhfggij** [orgzly-revived/orgzly-android-revived#228]
Device: Pixel 6a
    Android Version: 14
    Orgzly Revived Version: 1.8.19
    Repository type(s) used: fdroid

I may be completely mistaken, but it seems like headers need to have SCHEDULED: property for orgzly to push notifications when they are due. 

* So this shows notifications
SCHEDULED: <2024-04-21 Sun 16:00>
* But this won't
<2024-04-21 Sun 16:05>

It's important for me to be able to use "standalone dates" to avoid [repeating them in org-agenda on the desktop](https://emacs.stackexchange.com/questions/80965/hide-repeating-tasks-in-org-agendas-overdue-section).

**Comment by amberin** [comment]
Interesting. I think I agree that there should be a notification. The items do appear in the agenda, so it's confusing that there is no notification.

**Comment by pjhfggij** [comment]
Yeah, I thought that dates like this <2024-04-22 Mon 12:00> would trigger notifications and dates with square brackets ([2024-04-22 Mon 12:00]) would not. Now it looks like only SCHEDULED dates push notifications.

**Comment by amberin** [comment]
Ah, it does work but it's a setting which is off by default. I just verified myself. It's the third item from the top in the "Reminders" setting screen.

**Comment by pjhfggij** [comment]
sorry, you are right, I should have tested it better before submitting this issue. I don't know why it didn't seem to work before, but after trying a regular date and a repeating date both pushed notifications (after toggling the Events reminder in the options that you mentioned).

**Comment by pjhfggij** [comment]
@amberin sorry again, push notifications don't work for repeating events, e.g. <2024-04-11 Thu 08:00 +1h>
It only works once for the first time, but stops working on subsequent events (in this case every next hour).
I've created a new issue as this one got confusing.
