### ISSUE TITLE
No dropbox option

### ISSUE THREAD

**Issue by PepaBCN** [orgzly-revived/orgzly-android-revived#232]
Intalled today from F-Droid but app doesn't show Dropbox option to sync as it did the old original one and as it's said in documentation.

    Device: Samsung S5e
    Android Version: ?
    Orgzly Revived Version: 
    Repository type(s) used:

**Comment by BrianA-MN** [comment]
The F-Droid version does not have Dropbox as an option, as explained by the original developer, because F-Droid only allows open source solutions and blob, which Dropbox is not. If you want the Dropbox option then download from the Google Play Store. The new developers have not changed this status, i.e. added Dropbox to the repository options. Also note that autosync is not supported for Dropbox even if added. Cheers.

**Comment by amberin** [comment]
The above is correct, except Orgzly Revived is not yet available in the Play store. The APK can be downloaded from this repo's Releases page, and you can also install and update using [the Obtainium app](https://github.com/ImranR98/Obtainium?tab=readme-ov-file).

**Comment by PepaBCN** [comment]
Ooook! I've read something about not Dropbox but couldn't really understand what was that about. English isn't my mother language and I was tired. Sorry for that inconvenience (I hate asking for what was already explained!). Thanks a lot to all the community to maintain alive this app! 😍

**Comment by PepaBCN** [comment]
Did it and it has Dropbox option, but it doesn't work. It says "Dropbox not linked"! 🙈

**Comment by amberin** [comment]
Oh, that's right there is a bug which has been fixed in the latest beta release. I will make a proper release shortly.

**Comment by amberin** [comment]
Version 1.8.20 is now properly released, and it should have working Dropbox integration.

**Comment by PepaBCN** [comment]
Now it's Dropbox who gives an error! 🙈🤣🤣🤣🤣
![Screenshot_20240428-094923_Chrome](https://github.com/orgzly-revived/orgzly-android-revived/assets/168303103/b7ff48bc-d14d-4e64-b0f1-4b9d9184d69f)

**Comment by PepaBCN** [comment]
Wonderful! 1.8.21 links ok with Dropbox! Thanks a lot! 
Tell me if you need help to translate to Spanish (or even Catalan) this app or any other, please! I want to contribute in any way with you!
