### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [orgzly-revived/orgzly-android-revived#233]
Because there is the dropbox key in the apk. Could you please rebuild the apk without the key? Thanks!

**Comment by amberin** [comment]
Oh, I didn't think of that. Thank you for reporting! I will remove the Dropbox key from the Fdroid build.

**Comment by markokocic** [comment]
The latest release 1.8.21 is still missing in F-Droid.

**Comment by amberin** [comment]
I believe it usually takes a couple of days for new versions get built.

**Comment by linsui** [comment]
Could you please fix the apk file name?

**Comment by amberin** [comment]
Whoops, didn't notice that. Will look into what went wrong there. I wonder if F-Droid will pick up on this change.

**Comment by amberin** [comment]
Found the issue in the workflow file, I've updated my PR.

**Comment by linsui** [comment]
It works, thanks!
