### ISSUE TITLE
Push notifications don't work for recurring tasks

### ISSUE THREAD

**Issue by pjhfggij** [orgzly-revived/orgzly-android-revived#246]
I expected tasks with repeating timestamps to push notifications every time a tasks reoccurs. For example this tasks:
* My task
<2024-01-26 Fri 16:30 .+1w>

to push notifications every week on Friday at 16:30. Right now orgzly only pushes notification the first time (26th of January at 16:30 in this example), but not in the subsequent weeks?

Are these assumptions wrong or does it work this way for other users?

```
Device: Pixel 6a
Android Version: 14
Orgzly Revived Version: 1.8.19
Repository type(s) used: fdroid
```

**Comment by amberin** [comment]
Hi, isn't this the same issue as #230?

**Comment by pjhfggij** [comment]
Sorry, I wasn't sure if this should be a new issue or rename the previous one, as it's more general - neither SCHEDULED not plain timestamps trigger push notifications. I can close this one and edit the previous one if that'd be easier?

**Comment by amberin** [comment]
Ah, I see... Yeah, if you have found that the issue applies even when using the SCHEDULED property, I'd suggest updating the previous issue to reflect this find, and close this one. That should be the least confusing in the end. 👍
