### ISSUE TITLE
copy-paste selected note(s) to other apps (eg email app) / android copy-paste manager.

### ISSUE THREAD

**Issue by berteh** [orgzly-revived/orgzly-android-revived#261]
Hello. 
I'd love to be able to quickly share a few selected notes to other apps (typically send by email).

My ideal workflow would be something like:
- select 1 or more notes
- hit "copy", or new "export" button next to it other mechanism is involved
- open other "text" app (in my case : mail client), hit "paste" (from keyboard copy-paste manager)
- all selected notes titles get pasted as text (raw format would be OK), with their content, along with their children notes if expanded, recursively. Collapsed notes would not be exported.

**Comment by amberin** [comment]
Hello! Please take a look at #125, and see if you have anything to add there. So we keep everything in one place.

**Comment by berteh** [comment]
thanks @amberin, will merge into #125
