### ISSUE TITLE
App Often Crashing and Notification Failure since v1.8.22.

### ISSUE THREAD

**Issue by G-i-o** [orgzly-revived/orgzly-android-revived#270]
- I have searched for existing issues that may be the same as or related to mine.

Please complete the following information:

    Device: Google Pixel 3a
    Android Version: Lineage v21 (Android 14).
    Orgzly Revived Version: 1.8.22
    Repository type(s) used (e.g. directory, Dropbox, WebDAV): F-Droid

Since v1.8.22 the app seems to be crashing frequently. Moreover, and this may be a consequence, when the app isn't opened in the background, the notification don't work and the widget does not get updated.

The app has the notification permissions allowed.

The previous version, v1.8.21, was not having this issue.

Thank Your for keeping up the good work. :pray:

**Comment by amberin** [comment]
Thank you for reporting. This sounds really bad. We seem to be having multiple permission issues on Lineage, see also #200.

I'm afraid it's really hard to troubleshoot without a virtual device running Lineage, and I cannot build an image myself because I only have a laptop to work with.

**Comment by amberin** [comment]
If you can find a certain way to reproduce a crash or notification failure, that would be highly valuable.

**Comment by alexvorobiev** [comment]
I am having the same issue on Pixel 8 pro - the app is unusable. It either doesn't respond or crashes. I will be reinstalling the previous version.

**Comment by amberin** [comment]
@alexvorobiev wrote:

> I am having the same issue on Pixel 8 pro - the app is unusable. It either doesn't respond or crashes. I will be reinstalling the previous version.

Please provide as much information as possible so that we can identify the bug. Are you also running LineageOS, or the Pixel's stock Android? In what situations does the app crash or stop responding?

**Comment by amberin** [comment]
FWIW, I have a device with LineageOS 20 (Android 13), and v1.8.22 works for me there. 

There is something wrong with requesting permissions, though - I never got the "allow notifications" prompt, which is supposed to show when syncing if the permission has not been granted. I'll look into it. But once I had manually granted notifications permission, everything works fine. I've had no crashes.

Unfortunately, there is no LineageOS v21 build for my device.

**Comment by alexvorobiev** [comment]
> @alexvorobiev wrote:
> 
> > I am having the same issue on Pixel 8 pro - the app is unusable. It either doesn't respond or crashes. I will be reinstalling the previous version.
> 
> Please provide as much information as possible to help identify the bug. Are you also running LineageOS, or the Pixel's stock Android? In what situations does the app crash or stop responding?

I am on the stock Android 14. The app stops responding when I try to click on the checkboxes next to the Todo items.

**Comment by n-hebert** [comment]
Adding my report that my Pixel 7 Pro with stock Android 14 is seeing crashes and I can no longer receive timely notifications on the latest Orgzly 1.8.22. They mostly arrive delayed, when I open the app manually.

**Comment by amberin** [comment]
Please try v1.8.23 and see if the issues remain.

**Comment by n-hebert** [comment]
1.8.23 seems better. Notification loss was always a bit random, so I can't say for 100% but I'm optimistic.

**Comment by G-i-o** [comment]
Yes, 1.8.23 seems to be working now as it used to for me as well.
