### ISSUE TITLE
"Add timestamp" button

### ISSUE THREAD

**Issue by pjhfggij** [orgzly-revived/orgzly-android-revived#280]
It would be useful to have a "quick action"/button that would add a timestamp under cursor, for example:
[2024-06-14 Fri 18:33] This happened at this time and date

on doom emacs this action is bound to SPC m d T keys by default.

I would use it to write up progress of a given task in "Contents" field. 

Right now I'm typing it all manually each time which got tedious.

[X] I have searched for existing issues that may be the same as or related to mine.

**Comment by amberin** [comment]
Hm, pretty sure this is #273, no?

**Comment by pjhfggij** [comment]
yes, sorry, I've completely missed it
