### ISSUE TITLE
Git: .orgzlyignore blocks update of files in an unignored directory ("/* \n !/dir" pattern)

### ISSUE THREAD

**Issue by necto** [orgzly-revived/orgzly-android-revived#290]
Device: OnePlus 11
    Android Version: 14.0 (CPH2449_14.0.0.810(EX01))
    Orgzly Revived Version: 1.8.24 (fdroid)
    Sync repository type (directory/Dropbox/WebDAV/Git): Git

Orgzly successfuly fetches unignored files according to the pattern in .orgzlyignore but it fails to push any update to them.

Steps to reproduce:
1. Have a repository with the following files:
  - file1.org
  - gtd/my-inbox.org
  - .orgzlyignore containing:
    ```
    /*
    !/gtd
    ```
2. Configure orgzly-revived to use Git sync with this repository
3. Sync. Orgzly fetches the my-inbox.org file only (good!)
4. Modify my-inbox.org
5. Sync. Orgzly fails with the following message in the notification area:
> "Sync failed
> my-inbox: Repository filename matches a rule in .orgzlyignore"

I have conducted this test on a freshly created repository https://github.com/necto/orgzly-revived-test

If I use "positive-only" pattern like this one:
```
/file1.org
/file2.org
```
The sync kind-of works, but really does not because due to https://github.com/orgzly-revived/orgzly-android-revived/issues/146 it creates my-inbox.org in the top-level dir with the modified content instead of updating the one in the gtd/ directory.

If I do not use directories, sync works in both directions.

**Comment by amberin** [comment]
I believe the real issue is #146 and #175. That is, notebooks outside the root directory is not supported at all at this moment (although one easily gets that impression, since they are loaded, but they cannot be saved).

I am working on general subfolder support for all repo types (#175) right now.

**Comment by necto** [comment]
Thanks, @amberin!
I will close it as a duplicate of #146 and #175 .
