### ISSUE TITLE
Dropbox App Folder + Full Dropbox

### ISSUE THREAD

**Issue by JZL** [orgzly-revived/orgzly-android-revived#301]
- I have searched for existing issues that may be the same as or related to mine.

Hi,

Thanks for helping revive this project, I use it all the time and it's great!

This might be a niche request (and I got it working in a fork with the GH build) but I think it'd be great to have 2 versions of the dropbox app. One which can only access the App/ folder, and one which has access to the full dropbox contents. Being able to do only App folder is nice for sandboxing but I have org files spread across many folders. You also can't share App folder files with others as far as I can tell.

I think this only requires having a second `secrets.GITHUB_TOKEN` with a different option chosen on creation. It looks like the `r0adkll/sign-android-release`'s signing can also take a list of files to sign. It might even be able to use a `matrix` to not have too much duplication

**Comment by amberin** [comment]
Hm, interesting. I don't know Dropbox very well, and when I updated the auth code I got the impression that scoped/app access was the only way to go. But if not, then full access should be preferable, right? Or does app folder access have any advantages?

**Comment by JZL** [comment]
(Just to confirm what it looks like, when you use scoped App permission, it creates a new folder App/ in your dropbox, with a subfolder called Orgzly. And orgzly can only modify files within that folder)

I can double check but when creating a [new app](https://www.dropbox.com/developers/apps/create) I think you can choose between App Folder and Full Dropbox. I've only ever done it for personal use (where the key is valid for only me), maybe publishing a full dropbox access app is made more difficult.

I think the App folder option gives nice security in depth where even if orgzly went rogue, it could only access the files in that App/ folder. But it's maybe best for apps where they only interact with files created within the apps themselves. And I imagine people almost always use org-mode on emacs and orgzly, so would have  to point their Emacs to the new App/ folder just to use orgzly. 

I have a hack I put below in [1] in case it helps someone else get both scoped security and not have the restrictions of App folder.

Full access makes things easier although with the hypothetical security concerns. I think letting the user choose is a cool option but maybe complex. The most ideal solution would be to change the dropdown for adding a new remote repository and allow the user to choose between "full dropbox access" and "scoped". It would choose the correct app secret key accordingly. But that's a bigger change I don't personally know how to do and don't know how hard it is. Generating 2 apk's would be as simple as adding another step in the build process




[1] I share (with edit permissions) all the .org files in my main ("A") dropbox to a separate free dropbox account ('B'). The I login to orgzly on the "B" account so it can only edit the shared files. It also gives symlink like structure where A's files are scattered around but shared with B's root directory for orgzly.

**Comment by amberin** [comment]
I see. I agree with you that full access seems much more useful for our use case. I will look into switching.

**Comment by ofaurax** [comment]
Another use case in favor of full access: I setup a static website generated from org files, stored in Dropbox.

The website structure is fixed by the generation tool (Hugo).

So, orgzly needs to be linked to the directory `dropbox:/project/website/content/`, and I cannot have it under the `dropbox:/Apps/` dir.

Ideally, it would be nice to be able to access Full-access and App-restricted directories from the same app.

**Comment by domOrielton** [comment]
+1 for this. It took me an embassingly long time to work out that Orgzly Revived had written the sync files to the App folder - I still have both Orgzly and Orgzly Revived on my phone and couldn't work out why Orgzly Revived wasn't updating the same folder as Orgzly, even thought the Repositories path was the same for both.  For my usage, it definitely makes more sense to use the Full Access permission.

**Comment by amberin** [comment]
I have finally looked into this, and we will need to create a new app in the Dropbox developer console. This mean that users will need to re-link Orgzly to their Dropbox account upon the next Orgzly update. I think this is acceptable, right?

**Comment by JZL** [comment]
I can only speak for myself but I think so. Esp. because this app is for a more advanced audience, putting a note in the changelog  is probably sufficient. 

I also checked and under the `Branding` tab, you can put a description which hopefully pops up on the oauth screen. Can help reassure this is intended.

The other option (which requires changing the app's code, not config. Don't know how hard) is relabeling the current login   button as "App folder access" and making a new button for "full Dropbox access"; then allow the user to choose. Personally I think it's complicated for no benefit, but some users might appreciate hard sandboxing of what orgzly's (potentially untrusted) code can view+modify in your dbx.

Thanks for looking into this!

**Comment by JZL** [comment]
I guess the thing to test is what happens when the api key is changed and people try to resync (without realizing).

Does it error in a way people know to re-login, or is it a confusing error?

**Comment by amberin** [comment]
Yes, I didn't think of that. Users will need to move their org files out of the app folder before they are even visible to Orgzly, so we probably a very informative message to Dropbox repo users.

**Comment by isentropic** [comment]
Gosh took me a while to realize this issue too. Happy to see that orzgly got revived, I've been using the older version for a while now. Full dropbox access makes lots of sense for me too, the way it has been with the original orgzly app

**Comment by amberin** [comment]
I am trying to figure out how to switch over to full access without causing too great a disruption for users. When we build a new version with a different app ID, the app will update and suddenly no longer be linked to the user's Dropbox account.

When the user re-links to their account, the org files in their Dropbox account will have a new path/URL, and I'm not sure how disruptive this will be. But I suppose we can build a pre-release and let people try that out, trying to collect some feedback.

**Comment by isentropic** [comment]
Ideally then this feature would be a checkmark-like option and purely opt-in. Maybe for simplicity just add another sync repository type called `Dropbox-full-access`, and then with some patchnotes this should all become clear

**Comment by amberin** [comment]
I don't think we would want the complexity of multiple scopes, in the long run.

But I just did some tests and it seems that we can just replace the app identifier in our next release without causing any disruptions. The app identifier is only used when linking the app to your Dropbox account, so new users will get full scope, and old users will only get it when they unlink and re-link. That should be a decent UX - the user is in control and it shouldn't be too confusing.

**Comment by marczz** [comment]
I am among the users who want to access to some org-mode files, on Linux, Android, and IOS. For this I use a Dropbox folder to which I access on Linux Emacs with rclone, on iOS with Beorg, and on Android with thé legacy orgzly. I would like to Switch to orgzly-revived, that I yet use on a git repository with an Android an Linux clone. But I can not acces the Dropbox folder used by Beorg.
Allowing access to folder in root directory of Dropbox would be a great improvement for inter application collaboration.

**Comment by amberin** [comment]
I just released version 1.8.28, which has full access to the Dropbox root folder. Existing installations will need to be re-linked.

I hope this does not create too much confusion for those who currently keep Orgzly content in an app folder.

**Comment by marczz** [comment]
I installed v 1.8.28, purged my database, tried to unlink Orgzly Revived from Dropbox from the app. But it was still linked, so I unlinked it directly from my Dropbox account. But when trying to relink the app I get an error 500, and cannot achieve relinking

**Comment by marczz** [comment]
I uninstalled the app and reinstalled from scratch, when I try to link the app to Dropbox it ask me in thé browser to autorise full access for orgzly revived, and when I push thé button I get this error 500

**Comment by amberin** [comment]
> I uninstalled the app and reinstalled from scratch, when I try to link the app to Dropbox it ask me in thé browser to autorise full access for orgzly revived, and when I push thé button I get this error 500

If you could post a screenshot of that error message, it would be very helpful.

**Comment by marczz** [comment]
Dropbox does not allow me to take screenshots on android. But the full text of the message is 
"Error (500)
Something went wrong. Don't worry, your files are still safe and the Dropbox team has been notified. Check out our Status Page to see if there is a known incident, our Help Center and forums for help, or head back to home. "
To check it was not related to the state of the Dropbox Repository, I tried to an other repository with thé samedi result.

**Comment by amberin** [comment]
Yeah, I just created a new account and I get the same problem. Damn, need to figure out whats going on here.

**Comment by amberin** [comment]
Lol, I had missed the button in the "app console" which allows additional users to link with the app... I believe it works now, at least it did with my new account. :sweat_smile:

**Comment by marczz** [comment]
I confirm that now it works, we can now access any folder in our Dropbox, thank you it is a great improvement😊

**Comment by verdammelt** [comment]
I also want to say "THANKS!" Now I can fully switch to Orgzly Revived.

**Comment by JZL** [comment]
Thanks so much, it's really a testament to the great maintainers here that it was taken up so quickly :)

I'm very appreciative (I downloaded it so fast)! Closing the issue but can always reopen if you want for some reason

**Comment by ofaurax** [comment]
Thanks for the work, can we have a link to the branch/code of the fix?

**Comment by amberin** [comment]
> Thanks for the work, can we have a link to the branch/code of the fix?

@ofaurax Yeah, I would have linked to it, but it was purely a change in a secret which is used to identify our app during the linking process. So no code changes at all.
