### ISSUE TITLE
Different new note defaults per notebook

### ISSUE THREAD

**Issue by ngm** [orgzly-revived/orgzly-android-revived#317]
I would find it helpful to be able to have different new note defaults per notebook.

Some notebooks I use for task management, so I set default state as TODO and scheduled for today.

Some notebooks I use for notes, so I set default state as NOTE and no scheduled date.  

At present I have to switch the default settings back and forth depending which notebook I am currently in.

**Comment by amberin** [comment]
This should be tied a more general "support Emacs-style per-file settings" ticket, if we don't already have one.

**Comment by amberin** [comment]
Closing as a duplicate of #120.
