### ISSUE TITLE
App crashes when saving notes stating "Missing permission to schedule alarm", but all premissions are already allowed.

### ISSUE THREAD

**Issue by RowanDabron** [orgzly-revived/orgzly-android-revived#346]
- I have searched for existing issues that may be the same as or related to mine.

Please complete the following information:

    Device: Google Pixel 9
    Android Version: 14 (GraphenesOS)
    Orgzly Revived Version: 1.8.26 (f-droid)
    Sync repository type (directory/Dropbox/WebDAV/Git): not setup yet

Every time I save a note the app crashes, and every so often it crashes and I get the attached error log ([Error in Orgzly Revived 216a241ae00d.txt](https://github.com/user-attachments/files/17337924/Error.in.Orgzly.Revived.216a241ae00d.txt)) stating it is missing permission to schedule alarm, and when trying to set a reminder on a note I get a popup saying "Alarms and reminders permission needed: The app needs the alarms & reminders permission to set exact times for scheduled/deadline. Please grant the permission in the 'app info' screen." In app info in the phone settings there is no permission for alarms/reminders, and all other permissions are already allowed.

I am running current GrapheneOS so I am not sure if that is causing the issue or not. Not sure if it's useful or not to know, but the old abandoned Orgzly app doesn't have these crashes and doesn't require (or have an option for) an alarms/reminders permission, so maybe some difference there is causing them?

Thanks in advance, and thanks for maintaining the project overall!

**Comment by amberin** [comment]
There is a permission check which apparently does not work well on GrapheneOS. We will soon switch from Android 13 to 14 as the target - if we are lucky that could make this issue go away. Permissions is one of the things that change in a big way between Android API versions.

If it does not go away in the next version (1.8.28), please update here.

**Comment by RowanDabron** [comment]
@amberin Thanks for the response! I'll update when the next version is released.

**Comment by schlackenfuchs** [comment]
Version 1.8.29 installed, still the same.

**Comment by schlackenfuchs** [comment]
Yes, I tried after your post and it seems to work now.
I also use Android 15, the latest updates came on Nov. 7 and Nov. 4 -- so there was no change since my post.
I agree: "The issue has resolved itself it seems, but I am not sure how or why. " It's magic...

**Comment by amberin** [comment]
Could it be something specific to GrapheneOS, which has been updated without you being aware? Let's hope so...

**Comment by amberin** [comment]
When I look at the "app info" screen, I find this reminders permission under the "Advanced" heading near the bottom - not among the regular permissions.

**Comment by RowanDabron** [comment]
Ah yes I see it now, thank you. I suppose I should have looked harder, but it does seem a little counter intuitive to have a permission anywhere other than the permissions section. I'm also not sure why they consider it more advanced than the rest of the permissions, but anyway that's nothing to do with you guys.

It could be a GrapheneOS quirk, in which case I am happy if you want to close this, since it does seem fixed now for me anyway, and issues like this is part of life with an uncommon and somewhat different OS.

Thanks for your help!
