### ISSUE TITLE
unable to setup sync'ing to dropbox

### ISSUE THREAD

**Issue by emacs18** [orgzly-revived/orgzly-android-revived#349]
How do I setup my Galaxy S23 phone to sync with dropbox?
I have orgzly app setup to sync with dropbox.
I am unable to do the same with orgzly-revived app.

I have searched for existing issues that may be the same as or related to mine.

    Device: Galaxy S23
    Android Version: 14
    Orgzly Revived Version: 1.8.27
    Sync repository type (directory/Dropbox/WebDAV/Git): Dropbox

[Orgzly | Notes & To-Do Lists](https://www.orgzlyrevived.com/docs) has this instruction to sync with dropbox:

> The Dropbox app is not required for syncing, instead you will allow Orgzly to contact Dropbox on your behalf using the browser.
> 
> -   Go to `Settings`
> -   Click on `Sync`
> -   Click on `Repositories`
> -   Click on `Dropbox`  (if you already have some repositories, click the plus icon first)
> -   Enter the directory inside Dropbox (without "Dropbox" part)

Above says to click on "Dropbox".  However the orgzly-revived app on my Galaxy S23 phone only shows two icons labelled "WebDAV" and "Directory".  There is no entry named "Dropbox" to click on!
When I select Settings -> Sync -> Repositories option, I see the following:

-   "Create new repository for syncing your notebooks"
-   Clickable icon labelled "WebDAV" with icon with cloud shape
-   Clickable icon labelled "Directory" with a directory icon.

Nothing else follows this, i.e., there is no other icon to click on!

PS: I have used orgzly for many years where I sync'ed my org files via dropbox.  I'm just trying to do the same with orgzly-revived.  I installed F-Droid app for the first time on my phone.  I installed orgzly-revived app found on F-droid app.

**Comment by amberin** [comment]
This is expected; the app account has been frozen due to passing 50 connected clients without applying for production status. I will soon release a new build with a different app ID and full scope access.

**Comment by emacs18** [comment]
I uninstalled `orgzly-revived` which I installed using `f-droid`. I downloaded [orgzly-revived-1.8.27.apk](https://github.com/orgzly-revived/orgzly-android-revived/releases/download/v1.8.27/orgzly-revived-1.8.27.apk), then installed it. This version indeed had `Drobox` icon which I could click on, so I used it to add `/orgzly` path. When I click on `Link to Drobox` button, a page that starts with "Orgzly Revived would like to: &#x2026;" shows up along with `Cancel` or `Allow` buttons. When I click on `Allow` button, following error page shows up:

    Error (500)
    Something went wrong.  Don't worry, your files are still safe and the Dropbox team has been notified...

I still have my old `Orgzly` app still installed on my phone along with `Orgzly Revived` app. Dropbox syncing seems to work fine using `Orgzly`. So I unlinked dropbox from `Orgzly`. This did not make any difference. I still ran into above error when I tried to link dropbox to `Orgzly Revived`.

I tried to link dropbox back to `Orgzly`. It worked.

Thus I can drop then relink dropbox on `Orgzly`. However I cannot link dropbox on `Orgzly Revived`.

**Comment by amberin** [comment]
Yes, they are two completely different apps, as far as Dropbox is concerned.

> This is expected; the app account has been frozen due to passing 50 connected clients without applying for production status. I will soon release a new build with a different app ID and full scope access (see #301).

**Comment by emacs18** [comment]
I updated from 1.8.27 to 1.8.28.  Now I can sync with my dropbox directory.
Problem solved.  Thanks.
