### ISSUE TITLE
Publishing to Play Store

### ISSUE THREAD

**Issue by sdenaro** [orgzly-revived/orgzly-android-revived#35]
- I have searched for existing issues that may be the same as or related to mine.

I would like to use Orgzly Revived with data on my personal profile on Android but I am restricted to apps in the Play store. The standard Orgzly has an outstanding issue with ssh keys that prevents me from using it with git.

**Comment by cashpw** [comment]
Is there any interest by maintainers to publish on the Play Store? I can't comment on the complexity but it looks like [only a few steps](https://support.google.com/googleplay/android-developer/answer/9859152?hl=en) after an account is set up.

**Comment by amberin** [comment]
Yes, publishing on Play store is definitely the goal.

**Comment by amberin** [comment]
...but it's not being actively worked on right now. Any sort of help is welcome!

**Comment by pataquets** [comment]
Yes, please! As a bonus: we'll get back Dropbox sync without resorting to APK manual installation.
Thank you guys for reviving Orgzly!

Any progress? Any task breakdown which might make it more approachable for those interested in helping?

**Comment by amberin** [comment]
The biggest question for me is the practicalities of app ownership. To create a Play developer account, you need a Google account with 2FA. Whose account do we use? Sharing the credentials is not easy. The Github organization is 12 people who don't know each other at all...

I guess I'll create the account and then see if there are solutions for sharing app ownership somehow.

If anyone knows more or has experience, please share!

**Comment by dwoffinden** [comment]
Once created, you can add other accounts as admins: https://support.google.com/googleplay/android-developer/answer/9844686

**Comment by amberin** [comment]
I have now created a developer account and an app, and will upload the latest version shortly, so that we can conduct the mandatory "closed test" phase.

**Comment by amberin** [comment]
We will need e-mail addresses to 20 people who can test the app for 14 days, before we will be allowed to publish to production. Not sure how to collect those addresses in a good way...

**Comment by pataquets** [comment]
@amberin: Since neither have I done this before, a quick global Github search for similar issues popped out this one, which seems to me it will be useful:
https://github.com/MohamedBassem/hoarder-app/issues/6#issuecomment-2037912350
HTH.

**Comment by sdenaro** [comment]
@amberin I can beta test if you can come up with a way for me to pass along my email address.

**Comment by amberin** [comment]
There is now a link you can follow to join the test: https://play.google.com/apps/internaltest/4701342774943410653

I am not sure exactly how it works, and I can't really try it out with my own Google account... But everyone is welcome to try the link and see if they can install the test version. I suggest we use this [discussion thread](https://github.com/orgzly-revived/orgzly-android-revived/discussions/250) for solving any further issues.

**Comment by amberin** [comment]
I am waiting for the final review of the release of v1.8.28 to the production channel, i.e. general availability in the Play Store. Once it's released, all I know that remains here is

- [ ] add a play store button to the repo README
- [ ] update the play store button on the website
