### ISSUE TITLE
Copying and pasting headings is broken: “j5.h cannot be cast to v5.l”

### ISSUE THREAD

**Issue by decadent** [orgzly-revived/orgzly-android-revived#383]
- [x] I have searched for existing issues that may be the same as or related to mine.

    Device: Pixel 3a
    Android Version: 12
    Orgzly Revived Version: 1.8.28, from F-Droid
    Sync repository type (directory/Dropbox/WebDAV/Git): directory

If I cut or copy headings from one place and try to paste in another, Orgzly shows a floating message `j5.h cannot be cast to v5.l`, and the headings aren't pasted. (I presume it's lowercase ‘l’ at the end, but dunno for sure.)

This potentially entails data loss for people who have automatic sync enabled, if they cut the headings — since there's no function to undo that.

The problem has most likely appeared in v1.8.28, as I use copy-pasting somewhat regularly.

**Comment by amberin** [comment]
I've noticed the same thing.

I will find the dependency upgrade which caused this and revert it.

**Comment by amberin** [comment]
Crap, I cannot reproduce this on a virtual device. I've tried Pixel 7 with Android 15, Pixel 5 with Android 14, and Pixel 3a with Android 12. The issue is not there. I'll troubleshoot on my own Pixel 5.

**Comment by amberin** [comment]
The problem does not occur on a 1.8.28 debug build, so something is probably missing in the minified APK.

**Comment by amberin** [comment]
I'm having real trouble reproducing this... On my own phone, the 1.8.28 fdroid release APK installed via Obtainium has the bug, but if I build a signed release APK (minified) in Android Studio with the same code, and install that on my phone, the bug is not there... So I suppose there must be something in the Github Action build pipeline which is different...?

**Comment by amberin** [comment]
Aha, found it. It only happens when you have enabled "Use property for created-at time" in Sync settings.

**Comment by amberin** [comment]
I will try the Proguard rules suggested here: https://github.com/google/gson/issues/2736

**Comment by amberin** [comment]
Solved thanks to https://github.com/google/gson/blob/main/Troubleshooting.md#-classcastexception-when-using-deserialized-object

**Comment by decadent** [comment]
Thanks!

Btw, doesn't that Entry class suggest that anything outside the heading line and the properties drawer isn't copied? Namely, the scheduled date, the deadline, the clock. Idk how they're stored and serialized, though.

**Comment by amberin** [comment]
@decadent I believe that the things you mentioned fall into Orgzly's "properties" category.

**Comment by amberin** [comment]
For future reference, if this should come up again, here's someone who looked deeply into Gson vs R8: https://theapache64.github.io/posts/why-fullMode-hates-gson-so-much/
