### ISSUE TITLE
1.8.28 - Moving notes from one Notebook to another causes mis-formatting in the original Notebook

### ISSUE THREAD

**Issue by toridnyc** [orgzly-revived/orgzly-android-revived#385]
I frequently move completed tasks from one notebook to another, sort of a Done notebook. Since installing .28, when I move multiple items from one notebook to another, some of the tasks formatting is incorrect.

Have a look at the 2 files. Items are getting moved successfully, but not removed successfully from the file. Take a look at line number 33 on the “after move” file for the formatting issue. I would expect all of the items that I’ve moved to be deleted from the file.

[Archive.zip](https://github.com/user-attachments/files/17491988/Archive.zip)

Please complete the following information:

    Device: Pixel 7a
    Android Version: 15
    Orgzly Revived Version: 
    Sync repository type (directory/Dropbox/WebDAV/Git): local Android directory

**Comment by amberin** [comment]
This is very weird, and I'm trying to reproduce it but haven't succeeded. Are you moving the completed tasks using the "refile" functionality, or something else?

**Comment by toridnyc** [comment]
I press and hold to highlight items, then I use the button that I've
circled in the image.


 [image: Screenshot_20241030-063705.png]

**Comment by amberin** [comment]
@toridnyc The image that you attached did not make it into the resulting comment/post. :(

**Comment by toridnyc** [comment]
> @toridnyc The image that you attached did not make it into the resulting comment/post. :(

It should be there now
