### ISSUE TITLE
Cannot paste notes after cut/copy

### ISSUE THREAD

**Issue by vecchioBlister** [orgzly-revived/orgzly-android-revived#393]
Device: Samsung M32
    Android Version: 13
    Orgzly Revived Version: 1.8.28
    Sync repository type (directory/Dropbox/WebDAV/Git): WebDAV

I have recently updated directly from 1.8.18 (or thereabout) to 1.8.28 (fdroid).
Everything works, except I have noticed I can copy and cut notes, but can't paste them anymore (therefore losing them forever if cutting). Whenever I try to paste (no matter the notebook or headline level), I get this cryptic message:
`j5.h cannot be cast to v5.l`

![Screenshot_20241028_144020_Orgzly Revived](https://github.com/user-attachments/assets/fdf26c1c-da5c-4127-8664-86a0e8def9b1)

**Comment by amberin** [comment]
Hello! This is #383, which is fixed in the next version. If you could try out [the 1.8.29 beta](https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.29-beta.1), that would be very helpful.

**Comment by vecchioBlister** [comment]
Oh damn, sorry! I did actually look through all the open issues, but didn't find a matching one because it was already closed)

I just tried the update, and so far it's been fixed!
