### ISSUE TITLE
allow sync all org files in a WebDAV repositories recursively including all subfolders

### ISSUE THREAD

**Issue by galaxy-gao** [orgzly-revived/orgzly-android-revived#397]
- I have searched for existing issues that may be the same as or related to mine.

I manage org files like this:

---folder1
------folder1_1
---------file1.org
---------file2.org
------project_2
---------file3.org
---folder2
------folder2_1
---------file4.org

I will refactor this folder and file structure aperiodically.

Currently, orgzly-revived only read org files in the first folder level. With subfolder feature, I need add several WebDAV repositories.
It may work for some days. But after I refactor the structure, I have to recreate WebDAV repositories manually.

Is there any method to sync all org files in a WebDAV repositories recursively, including all subfolders?
Or could you consider adding this feature?
Thanks very much.

**Comment by amberin** [comment]
I suppose moving all these folders into a new top folder is out of the question? Because that should suffice...

**Comment by galaxy-gao** [comment]
I'd like to use an arbitrary directory structure in order to browse org files with a file explorer or through dired-mode.

The key problem is that directories are not fixed, but are created or modified dynamically based on work. 
Once modified, I need to modify it in the repositories accordingly. It's easy to forget.

**Comment by amberin** [comment]
Oh, I see, that looks like a bug. It looks like subfolders are not actually enabled. I suppose you've double checked that it's on? Because it would be reset to the default in your step 2, when you clear Orgzly's database...

**Comment by amberin** [comment]
I don't see why this would be a problem for Orgzly. It supports an infinite number of folder levels, theoretically.

**Comment by galaxy-gao** [comment]
Maybe I missed something. I will try to explain the details.

My orgzly version is: 1.8.27
And the option "Support repositorry subfolders" is turned on.

Here's what I do and the result:
1. create some folders and org files in webdev like this:
--subfolder (folder level1)
----subroot.org
----sub1 (folder level2)
------sub1.org
----sub2 (folder level2)
------sub2.org
2. clear database and add a repository: https://dav.xxxxxx.com/dav/mynotes/subfolder
3. refresh Notebooks
only subroot.org listed here.

I think it will be great if all org files under subfolder, include subroot.org, sub1.org, sub2.org can listed in Notebooks.

**Comment by amberin** [comment]
Not sure what's going on with the comments here - they appear in the wrong order... Maybe email replies with weird timestamps?

**Comment by galaxy-gao** [comment]
Yes, I've double checked that "Support repository subfolders" option is on.

I tested Dropbox, it works: all org files is list in Notebooks, including files in subfolders.
But webdav still not work. My webdav provider is jianguoyun, in chinese is 坚果云.

If somebody have tested other webdav provider, it maybe sth wrong with my webdav provider jianguoyun?

**Comment by galaxy-gao** [comment]
The subfolders feature is great, thanks very much!

**Comment by amberin** [comment]
> I tested Dropbox, it works: all org files is list in Notebooks, including files in subfolders. But webdav still not work.

We have [a number of unit tests](https://github.com/orgzly-revived/orgzly-android-revived/blob/master/shared-test/src/main/java/com/orgzly/android/repos/SyncRepoTest.kt) to check that subfolders are working, and they are run against all repository types.

Perhaps there is a setting somewhere which makes your cloud provider hide the subfolders?

You could try with a different cloud provider. A free one I've used for tests is [thegood.cloud](https://thegood.cloud/).

**Comment by galaxy-gao** [comment]
I tried [thegood.cloud](https://thegood.cloud/), it can retrieve correct count of all org files when test connection.
I use CyberDuck to connect my cloud provider jianguoyun, subfolders can list correctly. 
> Perhaps there is a setting somewhere which makes your cloud provider hide the subfolders?

Maybe that's why.

Now Dropbox works well for me, I will use it in current stage.
