### ISSUE TITLE
No "Sync progress" notification when syncing

### ISSUE THREAD

**Issue by lingnand** [orgzly-revived/orgzly-android-revived#428]
- I have searched for existing issues that may be the same as or related to mine.

Please complete the following information:

    Device: Microsoft Surface Duo 2
    Android Version: 12
    Orgzly Revived Version: 1.8.31
    Sync repository type (directory/Dropbox/WebDAV/Git): Git

This is a bit weird as I don't have this issue on my other phone which uses orgzly-revived in a same setup and runs Android 8.

When I trigger sync (either in app, or via an app shortcut, or via Tasker), no notification is seen. If I go into the app I can see it's indeed syncing. I've gone into app's Notification Setting and made sure "Sync progress" "Sync prompt" "Failed sync" are all turned on. Note that other notifications do work i.e., sync failure, reminders.

I also tried the old orgzly app on this phone and it doesn't have this issue (also using Git sync).

**Comment by amberin** [comment]
Yes! This has been bugging for sooo long, but I haven't had time to look into it!
