### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by rgri** [orgzly-revived/orgzly-android-revived#5]
This repo was started three weeks ago, and there has been some talk of setting up Github Actions. Is there any information on what could be holding up production of an APK? I'm very excited to try the new time clocking features, which are unavailable from google play.

**Comment by alensiljak** [comment]
We should see if it is possible to build an apk automatically. I think the main issue will be the signing key.

**Comment by amberin** [comment]
You can now find a build here. But be aware that the app name and ID here is just one among several suggestions, so it will likely change in a later build.

**Comment by amberin** [comment]
There is now a published "official" pre-release APK: https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.11-beta.2
