### ISSUE TITLE
Notification settings don't work

### ISSUE THREAD

**Issue by Ypot** [orgzly-revived/orgzly-android-revived#55]
- I have searched for existing issues that may be the same as or related to mine.

It is not possible to access the menu to choose the sound of the alarm.

**Comment by licaon-kter** [comment]
Can you detail the exact steps you take? Works fine for me on Android 13 here

**Comment by Ypot** [comment]
> Can you detail the exact steps you take? Works fine for me on Android 13 here

Can you check this screen recorded?
https://we.tl/t-3dvHlxpEy4

**Comment by amberin** [comment]
> > Can you detail the exact steps you take? Works fine for me on Android 13 here
> 
> Can you check this screen recorded? https://we.tl/t-3dvHlxpEy4
> 
> 1.8.12-beta.1 Android 13

Whoa, same for me. Must be something with the notification channels not lining up.

**Comment by licaon-kter** [comment]
In faireness I testes .11 not the betas, maybe this got broken after...

**Comment by amberin** [comment]
This may have been fixed by #73, but I haven't tested yet.

**Comment by amberin** [comment]
Confirmed as fixed by #73.
