### ISSUE TITLE
Notes are lost on cut and paste

### ISSUE THREAD

**Issue by kai11** [orgzly-revived/orgzly-android-revived#56]
- [X] I have searched for existing issues that may be the same as or related to mine.

I frequently move notes from Inbox to other notebooks.
If I cut one note then cut another note without pasting first, former  note is lost.

Im not sure is it a bug or feature request. This is certainly a problem for my workflow.
For now I'm using Nextcloud history and diff, but its cumbersome and requires notebook or desktop computer.

Options
1) add warning "current note in clipboard was not pasted, do you want to overwrite it?"
2) even better, full undo system?

**Comment by cbkerr** [comment]
One solution could be to remove "cut" and add another action called something like "paste and cut" or "cut to here".

This is what macOS does to make it explicity when you want to "move" something.

**Comment by alensiljak** [comment]
I don't think this is a bug, although it is a bit unintuitive.

The way to move notes to different notebooks is at the bottom. The icon looks like an inbox.

The cut and paste work only within the same file. I agree this is a bit strange but so far haven't seen a better proposal.

**Comment by amberin** [comment]
Cut and paste does work between notebooks. Although I agree that the Refile function seems more fit for the purpose. It's what I use, anyway.

**Comment by alensiljak** [comment]
Oh, wow, it does, indeed. At least for the note I tried now.
From what I remember, it did not paste anything when I tried it a while back so I concluded what I wrote above.
It does seem a bit redundant.

**Comment by kai11** [comment]
@alensiljak Yes, Refile is MUCH better fit for what Im trying to do. Thank you.

I think this should be added to Welcome to Orgzly doc.
