### ISSUE TITLE
Problems with Git repository

### ISSUE THREAD

**Issue by kai11** [orgzly-revived/orgzly-android-revived#58]
- I have searched for existing issues that may be the same as or related to mine.

Im testing version 1.8.11 and I have numerous problems with git repositories.

1) When I create git repo, message about missing ssh key disappears too quickly. Few first times I thought it was a simple crash.
2) I cannot create any ssh key
![Screenshot_20231107_102855_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/5407282/a6e18733-83c8-4379-98de-925c9cdc75b2)
![Screenshot_20231107_102902_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/5407282/b6730fd8-fd7a-4a3b-961d-8ea33073e207)
![Screenshot_20231107_102910_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/5407282/d48abe06-e12e-4133-b71a-aad7cf9e7ca2)

**Comment by amberin** [comment]
Thank you. I'll see if I can reproduce, and add some more logging where possible.

@kai11 What device and Android version are you using?

**Comment by anoduck** [comment]
Just to confirm, I am experiencing the same issue on my ancient Kyocera Duraforce with Android v6.103VZ.

**Comment by amberin** [comment]
I failed to reproduce this on a virtual Pixel 5 API 33 and on a new install of 1.8.11 on my own Pixel 5.

I tried both with and without screen lock protection.

I will add more logging in an upcoming version. We should at least be able to see the full stack trace in logcat.

**Comment by anoduck** [comment]
@amberin I am unsure what android version is covered by Pixel 5 API 33. Is not that Android 13? 

I also unsure about the specifics of @kai11 device, but my device is rather disgracefully one of those verizon wireless specific releases. For these devices, to my knowledge, rooting is unavailable. Would this have anything to do with the issue?

Or would the age be the cause?

I am just shooting in the dark, hoping I hit something. 

Sincerely, thanks for keeping the project alive. I had waited years for it's arrival.

**Comment by kai11** [comment]
Ok, waiting for next version with logs.
I also found out app logs (Settings > App > Developer Options > Logs) and I see nothing there either.

**Comment by kai11** [comment]
I also tested 1.8.12 and have the same problemss while trying to generate all 3 ssh key types - with and without fingerprint protection.

Nothing in logs either.

**Comment by alensiljak** [comment]
I don't get any errors but a git repository never gets registered. Hence I can't sync.
The folders get created, though.

**Comment by anoduck** [comment]
Wish I could be of some service. I don't know a lick of Java, barely know JavaScript.

**Comment by amberin** [comment]
I have made some progress with R8 and the missing classes. Bouncycastle needs to be added as a dependency. But now, even on with a debug build, I am unable to generate a ECDSA key -- I get a StreamCorruptedException in org.apache.sshd.common.config.keys.KeyUtils.getPublicKeyEntryDecoder(), where no suitable decoder can be found for the generated public key. I found this interesting recent PR in the MINA SSHD project: https://github.com/apache/mina-sshd/pull/345/files.

**Comment by amberin** [comment]
Funny thing, the difference between JGit versions is in practice that with 5.13.1, I can generate all key types except ECDSA, and with 6.7.0 (latest), I can generate all key types except ED25519.

**Comment by amberin** [comment]
SSH key generation now works. PR coming soon.

**Comment by kai11** [comment]
@amberin Same problem exists on my phone with v1.8.13-beta.1
Nothing in orgzly logs.

**Comment by amberin** [comment]
Cloning also has Proguard issues. It works in debug build, but not in release build. Some translation resource bundle cannot be looked up in the minified APK.

Interestingly, cloning seems faster with JGit 6.7 than 5.13. But I may be forgetting some other changed circumstance.

**Comment by alensiljak** [comment]
Is there a native git implementation available for binding?

**Comment by amberin** [comment]
@kai11 Please try with 1.8.13-beta.2 https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.13-beta.2

**Comment by kai11** [comment]
@amberin 1.8.13-beta4 generates ssh keys. I tested all 3 with and without fingerprint.
I think this issue can be closed. Thank you for fixing it.

**Comment by anoduck** [comment]
@amberin I can generate a key, which is awesome. Unfortunately, selecting Git from the repository options does not do anything. It is as if the link was dead or returning a blank value. If my device is too old, I understand. We all should praise whatever small victories we can.

**Comment by amberin** [comment]
> @amberin I can generate a key, which is awesome. Unfortunately, selecting Git from the repository options does not do anything. It is as if the link was dead or returning a blank value. If my device is too old, I understand. We all should praise whatever small victories we can.

Android 6 is supposed to handle the Git repo code, so this is interesting. I will create a virtual device and see if I can reproduce.

**Comment by anoduck** [comment]
@amberin Don't put too much effort into it, there is no rush. As I said before, now is time for a victory dance. I am more than occupied trying to pretend to be a lawyer.

**Comment by TheEccentricConnisure** [comment]
I am able to clone my repo properly but the cloned repo cannot be viewed by the app 
![Screenshot_2024-01-24-08-25-41-61_ed2cde8a5c8dee394aae50c5114b3a51](https://github.com/orgzly-revived/orgzly-android-revived/assets/70190820/300ab732-0365-4add-9d3c-68bfa5515a67)
But if I use the normal way like accessing via the mentioned directory (the same one with the cloned repo) I am able to access the notes. And I want to mention that I have two files(directory) in my repo one for my templates and one with my notes, is this causing an issue?

**Comment by amberin** [comment]
@TheEccentricConnisure Sounds funny. If Orgzly can load the org files when added as a "directory" repo, it should not have a problem loading the same files from a "Git" repo folder.

This issue has been closed and yours is a different problem, so it would be great if you could open a new one, please.

Do you mind sharing the folder- and filenames in the cloned repo?
