### ISSUE TITLE
Error in the F-Droid build

### ISSUE THREAD

**Issue by alensiljak** [orgzly-revived/orgzly-android-revived#60]
Just copying the issue from F-Droid GitLab for now. Did not check the code yet.

```
...
fdroidserver.exception.FDroidException: Package "com.orgzly" already exists
```

Possibly due to

https://github.com/orgzly-revived/orgzly-android-revived/blob/63b81eb4132622f3f1712cf4e358ec700867bf70/app/build.gradle#L7

Related to #7

**Comment by alensiljak** [comment]
Perhaps this would still be useful to resolve?

**Comment by amberin** [comment]
> There's a workaround in place with an F-Droid build configuration but maybe we can adjust the namespace to prevent something similar in the future? Perhaps this would still be useful to resolve, if it doesn't cause other issues.

Absolutely. I thought the applicationId was the important parameter. I also worried that the "namespace" might affect the Java class path resolution. I really don't know Java too well.

**Comment by amberin** [comment]
Trying to understand this. Reading this:

> if you want to change your package name, be aware that the package name (as defined by your project directory structure) should always match the package attribute in the AndroidManifest.xml file as shown below
Source: https://www.geeksforgeeks.org/android-package-name-vs-application-id/

I assume this means that if we change the package name in the AndroidManifest.xml, then we also need to change the folder structure in the code base?

**Comment by amberin** [comment]
Also found this:

> It is recommended that you do the following when setting the application ID:
> - Keep the application ID the same as the namespace. The distinction between the two properties can be a bit confusing, but if you keep them the same, you have nothing to worry about.
> - Don't change the application ID after you publish your app. If you change it, Google Play Store treats the subsequent upload as a new app.
> - Explicitly define the application ID. If the application ID is not explicitly defined using the applicationId property, it automatically takes on the same value as the namespace. This means that changing the namespace changes the application ID, which is usually not what you want.

**Comment by alensiljak** [comment]
I'm actually leaning towards not changing the namespace. Don't fix it if it ain't broken sort of thing.
There is a solution to the F-Droid build and that will not need to change for a foreseeable time.
Modifying the namespace is most-likely not going to bring any benefits whatsoever to the application itself. Perhaps we shouldn't be asking for trouble. :D
Also, no need to make this relatively large code change for 0 actual benefit.

If you have some time, sure, try it out. Perhaps we can learn something.

**Comment by amberin** [comment]
@alensiljak OK, I will not focus on that right now, then. I'm curious though, what is the solution for the F-Droid build? Because we haven't changed anything to accommodate them, right?

**Comment by alensiljak** [comment]
Correct. They have used a different build script or something along those lines. The one that works has been posted in the request on gitlab.

I was thinking this would be useful for us, mostly, but we're OK as long as we don't have to upgrade anything.

**Comment by alensiljak** [comment]
Or reopen if you'd still like to try it at some point.
