### ISSUE TITLE
Add the -dfroid.apk to the Releases

### ISSUE THREAD

**Issue by alensiljak** [orgzly-revived/orgzly-android-revived#61]
As suggested in https://gitlab.com/fdroid/rfp/-/issues/2562#note_1643222376, we should add the -fdroid.apk version to the Releases, for comparison / testing the reproducible builds.

Related to #7

**Comment by alensiljak** [comment]
@amberin, did you build the binaries in the Releases? Would you mind building and attaching the `-fdroid` apk build of the latest published version?
I'll need to set up my Android dev environment all over again.

**Comment by amberin** [comment]
All release artifacts are built using Github Actions, and currently, the fdroid flavor is not included. So it needs to be added, and then renamed to something nice with the -fdroid suffix. Feel free to suggest changes: https://github.com/orgzly-revived/orgzly-android-revived/blob/master/.github/workflows/release.yml#L29

**Comment by alensiljak** [comment]
Great! When you have a second, please do have a look at #64. Perhaps you might spot something I've overlooked.
