### ISSUE TITLE
Publishing on F-Droid

### ISSUE THREAD

**Issue by alensiljak** [orgzly-revived/orgzly-android-revived#7]
Let's see what is needed to get the app published on F-Droid.

**Comment by markamaze** [comment]
I've got a start looking into how to do this.

F-Droid runs through GitLab. The project would need to be merged with gitlab's fdroiddata repo to be made accessible on F-Droid. The source of this merge can come from github, however a gitlab account is required.

There is a free individual account, but ownership cannot be transferred, and groups cannot be created. This may be sufficient so long as the credentials can be passed on to future maintainers, but it may not be ideal. 

There is also an Open Source Program which can be applied for, which will give free access to gitlab ultimate, allowing for change of ownership as well as creating groups so more than one person has access. The requirements for the Open Source Program are having an OSI-approved open-source license, open-source dependencies, and public visibility settings for all projects. The application process requires a gitlab account and sending screenshots of license and visibility settings and can take 15 days for approval. 

Whether or not the Open Source Program account is preferred, we need to start with creating a gitlab account (either the free one, or there is a 30 free trial of the ultimate account if we apply for the Open Source Program right away). I don't mind putting in some work to set it up, but I'm not sure about creating the gitlab account. Obviously setting up an account in my own name would be undesirable for the goal of a community project.

**Comment by alensiljak** [comment]
Requested: https://gitlab.com/fdroid/rfp/-/issues/2562

**Comment by alensiljak** [comment]
The submission has been closed due to an error during build:

> [gradle/wrapper/gradle-wrapper.jar](https://github.com/orgzly-revived/orgzly-android-revived/blob/40457b4d134d017217bb1aafa7ea74b5764edd49/gradle/wrapper/gradle-wrapper.jar) cannot be verified as free software because it does not match any listed on the [official website](https://gradle.org/release-checksums/): e2b82129ab64751fd40437007bd2f7f2afb3c6e41a9198e628650b22d5824a14There is a gradle command for [upgrading](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper) the wrapper:

**Comment by alensiljak** [comment]
To fix: `CertUtil -hashfile pathToFileToCheck [HashAlgorithm]`

**Comment by alensiljak** [comment]
The current issue: unique applicationId.
https://gitlab.com/fdroid/rfp/-/issues/2562#note_1613865884

We need to come up with a specific application Id or request an ownership transfer.

**Comment by colonelpanic8** [comment]
@alensiljak lets file a ticket to come up with a new application id

**Comment by amberin** [comment]
@alensiljak @colonelpanic8 Do you understand what they refer to exactly with applicationId? Because we have already changed the ID here: https://github.com/orgzly-revived/orgzly-android-revived/blob/master/app/build.gradle#L14 That is what made Android consider ours a unique app.

**Comment by alensiljak** [comment]
@amberin To be honest, I don't. But I was going to check that out tomorrow. I assumed it was some setting in the Gradle file or something alike.
Thanks for the tip, I will try to understand a bit more and confirm tomorrow.

**Comment by alensiljak** [comment]
https://www.geeksforgeeks.org/android-package-name-vs-application-id/

**Comment by alensiljak** [comment]
OK, I've confirmed that the applicationId is indeed modified and unique to the project. The guys have confirmed and reopened the request. The bot screwed up. Those machines, quite unreliable.

**Comment by alensiljak** [comment]
I see Orgzly Revived in F-Droid app! 🎉

It is not yet visible on the web. Once it is, I suggest adding the F-Droid badge to the ReadMe.

**Comment by alensiljak** [comment]
The app should soon show up in the F-Droid repo!

**Comment by amberin** [comment]
@alensiljak Do you have any idea why it hasn't shown up?

**Comment by alensiljak** [comment]
> @alensiljak Do you have any idea why it hasn't shown up?

No, but I expect it to show up any time now.
Note that it is not Google with unlimited resources but an Open Source and self-funded project.

**Comment by alensiljak** [comment]
Here is the pull request for the main F-Droid data repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14033

And the docs for inclusion: https://f-droid.org/docs/Inclusion_How-To/

>Once the fdroiddata repository is updated on GitLab, it’s mostly just a matter of time before F-Droid’s official build server will fetch, build, and publish your application on the main F-Droid repository.

The app metadata was merged on Nov 13.

**Comment by alensiljak** [comment]
The build status page: https://monitor.f-droid.org/builds/build

In the Build Status tab, select the first item - `fdroid build`, then search for "orgzly"...

The build log: https://monitor.f-droid.org/builds/log/com.orgzlyrevived/177#site-footer
shows that the app was built successfully today, not sure which time zone:

>2023-11-15 01:52:24,526 INFO: success: com.orgzlyrevived

**Comment by alensiljak** [comment]
From the inclusion doc: 

What to Expect

When your application metadata is approved and accepted into the fdroiddata git repository on GitLab, it won’t immediately appear in the main F-Droid repository.

Provided that your application does not have any build problems, it would takes somewhere around 24 to 48 hours from fdroiddata merge until the application to appears in the main repository.[1](https://f-droid.org/en/forums/topic/how-fast-the-main-f-droid-repository-updates/) This timing limitation is due to the APK signing part of the build process, which requires human intervention on keystore access step.[2](https://f-droid.org/en/forums/topic/encouraging-f-droid-participation-by-developers/#post-17868)

Nevertheless, your application will not appear in f-droid.org’s Lastest Apps list just yet, even though people can now already search and download it: Once the application appeared in the main F-Droid repository, it would take another day before appearing on [Latest Apps list](https://f-droid.org/en/).

**Comment by alensiljak** [comment]
> /close as fixed?

Yes, I would say so. I closed it after the pull request got merged at the F-Droid repo. Not sure what was the concern, @amberin.

**Comment by licaon-kter** [comment]
It wasn't live _then_, but it is _now_

**Comment by amberin** [comment]
Yeah, I just wanted to confirm that it's fully live. Thank you for your efforts, @alensiljak! 👍

**Comment by IzzySoft** [comment]
@amberin first congrats to your F-Droid listing! At this point I'd usually remove the app from my repo, but your Readme still carries my badge. So what's your stance on this? Shall I go ahead with the removal – or is it important to you keeping your app in my repo as well?

**Comment by alensiljak** [comment]
@IzzySoft, @amberin I think the custom is, as Izzy wrote, to remove the app from his repo after listing on F-Droid. I think it saves resources and keeps things simple. And, since we don't publish pre-releases, we can go ahead with the removal. I can remove the badge from the readme today.
Thanks again to all involved for making this happen.

**Comment by IzzySoft** [comment]
My repo often serves as "staging area" for apps on their way to F-Droid.org. Apps can get listed much faster here, as I just take the APKs provided by the corresponding developers – so no build setup etc. required. From there, fine-tuning can happen as well (e.g. setting up Fastlane and see how it looks like in the client, getting rid of any "offending libs" which might block inclusion with F-Droid, etc). Some apps might not manage the latter for quite a while (or even longer) as establishing alternatives is sometimes not just "dropping in a replacement" (think e.g. replacing MLKit with ZXing, FCM with UnifiedPush etc) so it takes them longer, some have a library that has no FOSS pendant and thus never manage so they simply stay. A few even prefer to stay and not to go to F-Droid.org. Again others have their pre-releases here (so testers have easy access incl. automated updates) while stable releases go to F-Droid.org … quite a spectrum.

And as @alensiljak correctly points out, it's also a matter of resources: My repo runs on "personal space". So to offer the most, it should complement F-Droid.org instead of duplicating it. Though there are exceptions where a "double-listing" makes sense, I try to keep the overlap small. As long as my badge is present in an app's repo, I ask before removal for two reasons: 1) there maybe a point behind why it was kept (and double-listing wanted/warranted), plus 2) it would be weird to have a 404 there :wink:
