### ISSUE TITLE
Orgzly seems to recreate files deleted from the org-mode directory

### ISSUE THREAD

**Issue by LeafyLappa** [orgzly-revived/orgzly-android-revived#77]
- I have searched for existing issues that may be the same as or related to mine.

---

I want to start using orgmode as a personal GTD system. I came across this post on reddit:

https://www.reddit.com/r/orgmode/comments/14czljd/orgzly_orgmode_android_client_has_a_fatal_bug_for/

https://github.com/orgzly/orgzly-android/issues/287

This bug seems critical. I found related issues on this repo: #22 and #28 however they while seemingly related to the mechanism they don't seem to mention exactly the same problem.

Has this been fixed anyhow?

**Comment by amberin** [comment]
We should definitely be able to solve this with a prompt to delete the notebook from Orgzly, as suggested in https://github.com/orgzly/orgzly-android/issues/287.

The first step is to add this sync status, something like BOOK_WITH_LINK_AND_ROOK_DOES_NOT_EXIST. And then prompt the user from com.orgzly.android.sync.SyncUtils#syncNamesake, and delete or keep the local notebook accordingly.

**Comment by amberin** [comment]
I am working on this.
